# Project configuration for foil_case_study
# Adjust paths if running on a different system

paths:
  raw_data: "/home/alyona/personal_projects/foil_case_study/data/online_retail_raw.csv"
  transactions: "/home/alyona/personal_projects/foil_case_study/data/transactions.csv"
  cancellations: "/home/alyona/personal_projects/foil_case_study/data/cancellations.csv"
  outliers: "/home/alyona/personal_projects/foil_case_study/data/outliers.csv"
  warehouse: "/home/alyona/personal_projects/foil_case_study/data/warehouse"
  fact_sales: "fact_sales.parquet"
  dim_customers: "dim_customers.parquet"
  dim_products: "dim_products.parquet"
  dim_time: "dim_time.parquet"
  outliers_parquet: "outliers.parquet"
  profiling_report: "/home/alyona/personal_projects/foil_case_study/docs/raw_data_profile.csv" 

outlier_thresholds:
  quantity: 5000
  unit_price: 250